trigger:
- main
variables:
  azureSubscription: '60c44961-5e43-4545-8dec-800ae7a7f22d'
  azureResourceGroup: 'aks-flask-rg'
  azureCluster: 'aks-flask'
stages:
- stage: Build
  jobs:
  - job: BuildImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'biju-acr-service-connection-serviceprincipal'
        repository: 'flask-api'
        command: 'buildAndPush'
        Dockerfile: 'app/Dockerfile'
        tags: 'latest'
- stage: Deploy
  jobs:
  - job: DeployHelm
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(azureResourceGroup) --name $(azureCluster)
          helm upgrade --install flask-app ./helm/flask-chart --set image.repository=bijuregristrynew.azurecr.io/flask-api,image.tag=latest
