trigger:
- main

variables:
  azureSubscription: 'Your-Service-Connection'
  azureResourceGroup: 'aks-flask-rg'
  azureCluster: 'aks-flask'

stages:
- stage: Build
  jobs:
  - job: BuildImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'bijuregistrynew.azurecr.io'
        repository: 'flask-api'
        command: 'buildAndPush'
        Dockerfile: 'app/Dockerfile'
        tags: 'latest'

