# .github/workflows/export-azure-to-tf.yml
name: Export Azure RG to Terraform

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
  # You could also trigger on a schedule or push to a specific branch if desired
  # schedule:
  #   - cron: '0 0 * * *' # Run daily at midnight UTC

env:
  # --- IMPORTANT: Configure these variables ---
  AZURE_RESOURCE_GROUP_TO_EXPORT: "rg-adf-central" # Replace with the name of your Azure RG
  # ------------------------------------------

permissions:
  id-token: write # Required for Azure login with OIDC
  contents: write # Required to push changes back to the repository

jobs:
  export_terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
